<div class="sect1">
<h2 id="_description">Description</h2>
<div class="sectionbody">

</div>
</div>
<div class="sect1">
<h2 id="_why_is_this_an_issue">Why is this an issue?</h2>
<div class="sectionbody">
<div class="paragraph">
<p>If an exception is already being thrown within the <code>try</code> block or caught in a <code>catch</code> block, throwing another exception in the <code>finally</code> block will override the original exception.
This means that the original exception&#8217;s message and stack trace will be lost, potentially making it challenging to diagnose and troubleshoot the root cause of the problem.</p>
</div>
<div class="listingblock">
<div class="content">
<pre class="highlight"><code class="language-vbnet" data-lang="vbnet">Try
    ' Some work which end up throwing an exception
    Throw New ArgumentException()
Finally
    ' Cleanup
    Throw New InvalidOperationException() ' Noncompliant: will mask the ArgumentException
End Try</code></pre>
</div>
</div>
<div class="listingblock">
<div class="content">
<pre class="highlight"><code class="language-vbnet" data-lang="vbnet">Try
    ' Some work which end up throwing an exception
    Throw New ArgumentException()
Finally
    ' Cleanup without throwing
End Try</code></pre>
</div>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_resources">Resources</h2>
<div class="sectionbody">
<div class="sect2">
<h3 id="_documentation">Documentation</h3>
<div class="ulist">
<ul>
<li>
<p><a href="https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/">Exceptions and Exception Handling</a></p>
</li>
<li>
<p><a href="https://learn.microsoft.com/en-us/dotnet/standard/exceptions/how-to-use-finally-blocks">Finally blocks</a></p>
</li>
<li>
<p><a href="https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/exceptions/how-to-execute-cleanup-code-using-finally">How to execute cleanup code using finally</a></p>
</li>
</ul>
</div>
<hr>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_implementation_specification">Implementation Specification</h2>
<div class="sectionbody">
<div class="paragraph">
<p>(visible only on this page)</p>
</div>
<div class="sect2">
<h3 id="_message">Message</h3>
<div class="paragraph">
<p>Refactor this code to not throw exceptions in finally blocks.</p>
</div>
<hr>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_comments_and_links">Comments And Links</h2>
<div class="sectionbody">
<div class="paragraph">
<p>(visible only on this page)</p>
</div>
<div class="sect2">
<h3 id="_on_29_jul_2013_235740_ann_campbell_wrote">on 29 Jul 2013, 23:57:40 Ann Campbell wrote:</h3>
<div class="paragraph">
<p>There&#8217;s no compliant example. Is that okay?</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_30_jul_2013_064149_freddy_mallet_wrote">on 30 Jul 2013, 06:41:49 Freddy Mallet wrote:</h3>
<div class="paragraph">
<p>Indeed Ann, that&#8217;s fine to not have a compliant example.</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_2_aug_2013_144930_dinesh_bolkensteyn_wrote">on 2 Aug 2013, 14:49:30 Dinesh Bolkensteyn wrote:</h3>
<div class="paragraph">
<p>Implemented by https://jira.codehaus.org/browse/SONARJAVA-251</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_7_jun_2023_141500_cristian_ambrosini_wrote">on 7 Jun 2023, 14:15:00 Cristian Ambrosini wrote:</h3>
<div class="paragraph">
<p>During a LaYC sprint, I removed dummy implementations for the following language:</p>
</div>
<div class="ulist">
<ul>
<li>
<p>flex</p>
</li>
<li>
<p>javascript</p>
</li>
<li>
<p>php</p>
</li>
<li>
<p>python</p>
</li>
</ul>
</div>
<div class="paragraph">
<p>It is not implemented in the corresponding analyzer and there currently are no tickets open to do so.
Moreover, I also extended the new rule description for Java and CFamily.</p>
</div>
</div>
</div>
</div>